-- MySQL Script generated by MySQL Workbench
-- Mon May 30 15:23:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tulugar` DEFAULT CHARACTER SET utf8 ;
USE `tulugar` ;

-- -----------------------------------------------------
-- Table `tulugar`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `max_guests` TINYINT UNSIGNED NULL,
  `price` INT UNSIGNED NOT NULL,
  `description` VARCHAR(255) NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(100) NULL,
  `address` VARCHAR(255) NULL,
  `type` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tulugar`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(12) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `type` VARCHAR(14) NULL,
  `avatar` VARCHAR(255) NULL DEFAULT 'default.jpg',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `tulugar`.`amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`amenities` (
  `product_id` INT UNSIGNED NOT NULL,
  `wifi` TINYINT UNSIGNED NULL DEFAULT 0,
  `room_service` TINYINT UNSIGNED NULL DEFAULT 0,
  `breakfast` TINYINT UNSIGNED NULL DEFAULT 0,
  `pets` TINYINT UNSIGNED NULL DEFAULT 0,
  `garage` TINYINT UNSIGNED NULL DEFAULT 0,
  `linens` TINYINT UNSIGNED NULL DEFAULT 0,
  `heating` TINYINT UNSIGNED NULL DEFAULT 0,
  `air_conditioning` TINYINT UNSIGNED NULL DEFAULT 0,
  `pool` TINYINT UNSIGNED NULL DEFAULT 0,
  `grill` TINYINT UNSIGNED NULL DEFAULT 0,
  INDEX `fk_amenities_idx` (`product_id` ASC) INVISIBLE,
  CONSTRAINT `fk_amenities_pid`
    FOREIGN KEY (`product_id`)
    REFERENCES `tulugar`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tulugar`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`bookings` (
  `product_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `checkin` VARCHAR(45) NULL,
  `checkout` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `status` VARCHAR(10) NULL,
  INDEX `fk_bookings_products_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_bookings_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_pid`
    FOREIGN KEY (`product_id`)
    REFERENCES `tulugar`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `tulugar`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tulugar`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`images` (
  `product_id` INT UNSIGNED NOT NULL,
  `image1` VARCHAR(255) NULL DEFAULT 'default.jpg',
  `image2` VARCHAR(255) NULL,
  `image3` VARCHAR(255) NULL,
  `image4` VARCHAR(255) NULL,
  `image5` VARCHAR(255) NULL,
  `images6` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_images_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_pid`
    FOREIGN KEY (`product_id`)
    REFERENCES `tulugar`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tulugar`.`products_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`products_users` (
  `product_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`, `user_id`),
  INDEX `fk_pu_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_pu_products_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_pu_pid`
    FOREIGN KEY (`product_id`)
    REFERENCES `tulugar`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pu_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `tulugar`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
