-- MySQL Script generated by MySQL Workbench
-- Mon May 30 15:23:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tulugar` DEFAULT CHARACTER SET utf8mb4;
USE `tulugar` ;

-- -----------------------------------------------------
-- Table `tulugar`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(12) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `type` VARCHAR(14) NULL,
  `avatar` VARCHAR(255) NOT NULL DEFAULT 'default.jpg',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  UNIQUE INDEX `uidx_users_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uidx_users_username` (`username` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tulugar`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `max_guests` TINYINT UNSIGNED NULL,
  `price` INT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(100) NULL,
  `address` VARCHAR(255) NULL,
  `type` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `tulugar`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tulugar`.`amenities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`amenities` (
  `product_id` INT UNSIGNED NOT NULL,
  `wifi` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `room_service` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `breakfast` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `pets` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `garage` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `linens` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `heating` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `air_conditioning` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `pool` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `grill` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `uidx_amenities_pid` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_amenities_pid`
    FOREIGN KEY (`product_id`)
    REFERENCES `tulugar`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tulugar`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`bookings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `checkin` DATE NOT NULL,
  `checkout` DATE NOT NULL,
  `price` INT NULL,
  `status` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_bookings_uid_pid` (`user_id`, `product_id`) VISIBLE,
  CONSTRAINT `fk_bookings_pid`
    FOREIGN KEY (`product_id`)
    REFERENCES `tulugar`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `tulugar`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tulugar`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tulugar`.`images` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT 'default.jpg',  
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_images_pid`
    FOREIGN KEY (`product_id`)
    REFERENCES `tulugar`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
